Issue #2 Adding tests for error handling use case

diff --git a/src/test/resources/ansible b/src/test/resources/ansible
--- a/src/test/resources/ansible
+++ b/src/test/resources/ansible
@@ -1,3 +1,9 @@
 #!/bin/bash
 
-echo "ansible $@" > output
+if [ "$2" == "ERROR" ]
+then
+  >&2 echo "ERROR: ansible $@"
+  exit 1
+else
+  echo "ansible $@" > output
+fi
diff --git a/src/test/resources/ansible-playbook b/src/test/resources/ansible-playbook
--- a/src/test/resources/ansible-playbook
+++ b/src/test/resources/ansible-playbook
@@ -1,3 +1,9 @@
 #!/bin/bash
 
-echo "ansible-playbook $@" > output
+if [ "$2" == "ERROR" ]
+then
+  >&2 echo "ERROR: ansible-playbook $@"
+  exit 1
+else 
+  echo "ansible-playbook $@" > output
+fi
